---
title: "X-Y gametologs - DNA - mapping bias"
output: html_notebook
---

# repeat x-y analysis with DNA
is there mapping bias?
weird genes where females map to the Y?
tbd
```{r}
library(tidyverse)
```


```{r}
dnaColnames<-colnames(dnaCounts) 
dnaColnamesRepaired<- gsub("NS\\.[0-9]+\\.[0-9]+.IDT_i._\\d+---IDT_i._\\d+\\.(\\d+[a-z]+[FM])LD_sortMarkDups.*", "\\1", dnaColnames)
colnames(dnaCounts)<-dnaColnamesRepaired

dnaCountsClean <- dnaCounts %>% 
  select(-"40aF",-"24fM",-"35aM") %>%
  relocate(1:6,ends_with("F"), ends_with("M")) %>%
  mutate(Chr = ifelse(grepl("X",Chr), "X",
              ifelse(grepl("Y",Chr), "Y",
              ifelse(grepl("A1",Chr), "A1",
              ifelse(grepl("A2",Chr), "A2",
              ifelse(grepl("A3",Chr), "A3",
              ifelse(grepl("A4",Chr), "A4", NA))))))) %>% 
  rowwise() %>% 
  mutate(totalCountsGene = sum(c_across(7:155))) %>% 
  mutate(meanCounts = totalCountsGene/149) %>%
  mutate(femaleCountsTotal = sum(c_across(contains("F", ignore.case = FALSE)))) %>%
  mutate(female_mean = femaleCountsTotal/74) %>%
  mutate(maleCountsTotal = sum(c_across(contains("M", ignore.case = FALSE)))) %>%
  mutate(male_mean = maleCountsTotal/75) %>% 
  relocate(1:6,totalCountsGene, meanCounts, femaleCountsTotal, female_mean, maleCountsTotal,male_mean )
```
